pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "gowshik204/airbnb-clone-backend"
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/GOWSHIK-2004/airbnb-clone.git'
            }
        }

        stage('Setup Environment') {
            steps {
                writeFile file: '.env', text: """
                PORT=5001
                CONNECTION_STRING=mongodb+srv://skalpha:18102004@shanthakumar-cluster.g6rh7.mongodb.net/?retryWrites=true&w=majority&appName=shanthakumar-cluster
                ACCESS_TOKEN_SECRET=shanthakumar-airbnb-clone-2024
                COOKIE_SECURE_STATE=false
                COOKIE_SAME_SITE=lax
                """
            }
        }

       stage('Install Dependencies') {
    steps {
        script {
            def nodejs = tool name: 'nodejs-18', type: 'jenkins.plugins.nodejs.tools.NodeJSInstallation'
            env.PATH = "${nodejs}/bin:${env.PATH}"
        }
        dir('backend') {
            sh 'npm install --only=production'
        }
    }
}


        steps {
    dir('backend') { 
        sh '''
        docker build -t gowshik204/airbnb-clone-backend -f Dockerfile .
        '''
        withDockerRegistry([credentialsId: 'docker-hub-credentials', url: '']) {
            sh '''
            docker push gowshik204/airbnb-clone-backend:latest
            '''
        }
    }
}

        stage('Deploy Backend') {
            steps {
                sh '''
                docker stop airbnb-backend || true
                docker rm airbnb-backend || true
                docker run -d --name airbnb-backend -p 5001:5001 --env-file .env gowshik204/airbnb-clone-backend:latest
                '''
            }
        }
    }

    post {
        success {
            echo "✅ Backend deployed successfully!"
        }
        failure {
            echo "❌ Build or deployment failed!"
        }
    }
}
